### ISSUE TITLE
Update to the latest phridge

### ISSUE THREAD

**Issue by XhmikosR** [giakki/chai-resemble#3]
So that we get the latest phantomjs-prebuilt.

https://github.com/peerigon/phridge/compare/v1.2.2...master

/CC @giakki

**Comment by XhmikosR** [comment]
Bump @giakki

**Comment by XhmikosR** [comment]
@giakki: bump, bump

**Comment by RyanZim** [comment]
@XhmikosR PR welcome

**Comment by XhmikosR** [comment]
I tried doing this with no success. Someone should tackle this since

1. we will be able to use the latest phantomjs
2. we should be able to drop when dep and use native Promises

**Comment by giakki** [comment]
Done (I switched to puppeteer). I'll look into integrating this with UnCSS tomorrow.

Cheers!
